### PR TITLE
Prepare for Herwig kt-hard production

### PR DESCRIPTION
**Pull request by mfasDa**
- Add kt-hard as parameter
- Rename sim logfile from sim.log to hwgsim.log
  in order to not overwrite the simulation
  logfile in dpgsim
- Add parameters k and K to aligenmc
  steering min and max kt hard

### CODE REVIEW

**Comment by mfasDa** [comment]
@preghenella @maireiphc Can you please check whether this can be merged?

**Review by preghenella — APPROVED** [review]

**Comment by mfasDa** [comment]
Eventually only @qgp can merge into the repository.

**Comment by mfasDa** [comment]
The second change should be merged as well: If one calls alienv without --no-refresh then concurrent write operations can occur in batch mode as alienv updates the module directory.

**Comment by maireiphc** [comment]
Hi @mfasDa,

 in https://github.com/alisw/aligenmc/blame/master/gen/herwig/gen.sh, l.4, there is the choice of the package Herwig version.
Currently PACKAGES="Herwig::v7.1.2-alice1-3"

You may want to update the package version of Herwig on the way (?).
Thanks to you, we are now by default on Herwig::v7.2.0 (Herwig::v7.2.0-4 in details)
Or do you want have a separate and later PR for this ?

**Comment by mfasDa** [comment]
Hi @maireiphc,

Thanks a lot for spotting! I will update the version and and update the PR.

Cheers

Markus

**Pull request merged**
